### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by knil-sama** [knil-sama/caeli#2]
- [x] Split github api and database api in 2 separate file => #8 
- [x] find a way to remove literal sql query in code, put them in /sql #10 
- [x] reduce some function that are too big => #9
